In [ ]:
import pandas as pd
data=pd.read_csv('https://modcom.co.ke/data/datasets/pima.csv')
data

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Not Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic
3,1,89,66,23,94,28.1,0.167,21,Not Diabetic
4,0,137,40,35,168,43.1,2.288,33,Diabetic
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,Not Diabetic
764,2,122,70,27,0,36.8,0.340,27,Not Diabetic
765,5,121,72,23,112,26.2,0.245,30,Not Diabetic
766,1,126,60,0,0,30.1,0.349,47,Diabetic
767,1,93,70,31,0,30.4,0.315,23,Not Diabetic

In [ ]:
data.isnull().sum()

Children                    0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
data.groupby('Outcome').size()

Outcome
Diabetic        268
Not Diabetic    500
dtype: int64

In [ ]:
data.describe()

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

In [ ]:
array = data.values
X = array[:,0:8]
Y = array[:, 8]

In [ ]:
#model selection
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.30, random_state=42)

In [ ]:
#algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

In [ ]:
#cross validation

In [ ]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [ ]:
#testing 
predictions = model.predict(X_test)
print('We have predicted', predictions)

We have predicted ['Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic']

In [ ]:
print('The accurate answers are', Y_test)

The accurate answers are ['Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic']

In [ ]:
#accuracy estimation
from sklearn.metrics import accuracy_score
print('ACCURACY: ', accuracy_score(predictions, Y_test))

ACCURACY:  0.7142857142857143

In [ ]:
#PREDITIONS

symptoms = [[2,100,50,30,1,20,0.50,28]]
disease = model.predict(symptoms)
print('You are 74% likely to be', disease)

You are 74% likely to be ['Not Diabetic']

In [ ]:
data.head(2)

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Not Diabetic